/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CongregacionBD;

import CongregacionBE.MiBuscadorBE;
import ejecutar.Coneccion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;

/**
 *
 * @author Loyola
 */
public class p_MiBuscador_ins {
    private int Accion;
    private int Id_MiBuscador ;
    private String Codigo ;
    private String Descripcion ;
    private Date Fecha ;
    private int ReturnVal;

    public p_MiBuscador_ins(Coneccion strCn,MiBuscadorBE objMiBuscadorBE) throws SQLException {
        this.Accion = objMiBuscadorBE.getAccion();
        this.Id_MiBuscador = objMiBuscadorBE.getId_MiBuscador();
        this.Codigo = objMiBuscadorBE.getCodigo();
        this.Descripcion = objMiBuscadorBE.getDescripcion();
        this.Fecha = objMiBuscadorBE.getFecha();
        this.ReturnVal = objMiBuscadorBE.getReturnVal();
        Connection con = strCn.getCon();
        Statement st=null;
        ResultSet rs=null; 
        try {            
            con.setAutoCommit(false);
            st = con.createStatement();
            //        this.ReturVal = ReturVal;
            if (this.Accion == 1){
                
                rs=st.executeQuery("SELECT max(ID_MiBuscador) FROM MiBuscador");
                int idValidAnterior=0;
                while (rs.next()) {
                    idValidAnterior=rs.getInt(1);                    
                }
//              st.executeUpdate("CREATE TABLE USUARIO(Id_Usuario INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,Nombre VARCHAR(100),Password VARCHAR(100))");
                
                st.executeUpdate("INSERT INTO MiBuscador  (Codigo,Descripcion,Fecha)VALUES("+
                    "'"+this.Codigo+"'"+
                    ",'"+this.Descripcion+"'"+
                    ",'"+this.Fecha.getYear()+"-"+(this.Fecha.getMonth()+1)+"-"+this.Fecha.getDate()+"')");
                rs=st.executeQuery("SELECT max(ID_MiBuscador) FROM MiBuscador");
                int idActual=0;
                while (rs.next()) {
                    idActual=rs.getInt(1);                    
                }
                this.ReturnVal=-1;
                if (idValidAnterior<idActual) {
                    this.ReturnVal=idActual;
                }
//                st.close();               
            }
            if (this.Accion == 2){//CREACION DE UNA TABLA FISICA EN UNA BASE DE DATOS
              st.executeUpdate("CREATE TABLE MiBuscador(" +
                                "    Id_MiBuscador int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY" +
                                "    ,Codigo varchar(32000) " +
                                "    ,Descripcion varchar(32000) " +
                                "    ,Fecha Date " +
                                " )");
//              st.close(); 
              this.ReturnVal=0;
            }
            if (this.Accion == 3){//ELIMINACION DE UNA TABLA FISICA EN UNA BASE DE DATOS
              st.executeUpdate("DROP TABLE MiBuscador");
//              st.close(); 
              this.ReturnVal=0;
            }
            con.commit();
            con.setAutoCommit(true);
            st.close();
        } catch (Exception e) {
            con.rollback();
            con.setAutoCommit(true);
            st.close();
            System.out.println(e);
            this.ReturnVal=-1;
        }
    }
    public p_MiBuscador_ins(Connection strCn,MiBuscadorBE objMiBuscadorBE) {
        this.Accion = objMiBuscadorBE.getAccion();
        this.Id_MiBuscador = objMiBuscadorBE.getId_MiBuscador();
        this.Codigo = objMiBuscadorBE.getCodigo();
        this.Descripcion = objMiBuscadorBE.getDescripcion();
        this.Fecha = objMiBuscadorBE.getFecha();
        this.ReturnVal = objMiBuscadorBE.getReturnVal();
    }

    public int getReturnVal() {
        return ReturnVal;
    }

    public void setReturnVal(int ReturnVal) {
        this.ReturnVal = ReturnVal;
    }
    
}