package CongregacionBD;

import CongregacionBE.UsuarioBE;
import ejecutar.Coneccion;
import java.sql.*;
import java.util.Random;

/**
 *
 * @author Loyola
 */
public class p_Usuario_ins {
    private int Accion;
    private int Id_Usuario;
    private String Nombre;
    private String Password;
    private String FlagActivo;
    private int ReturnVal;

    public p_Usuario_ins(Coneccion strCn,UsuarioBE objUsuarioBE) {
        this.Accion     = objUsuarioBE.getAccion();
        this.Id_Usuario = objUsuarioBE.getId_Usuario();
        this.Nombre     = objUsuarioBE.getNombre();
        this.Password   = objUsuarioBE.getPassword();
        this.FlagActivo = objUsuarioBE.getFlagActivo();
        Statement st=null;
        try {
            st = strCn.getSt();
            
            //        this.ReturVal = ReturVal;
            if (this.Accion == 1){
//              st.executeUpdate("CREATE TABLE USUARIO(Id_Usuario INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,Nombre VARCHAR(100),Password VARCHAR(100))");
                st.executeUpdate("INSERT INTO USUARIO (Nombre ,Password,FlagActivo )VALUES("
                        + "'"+ this.Nombre + "'"
                        + ",'"+this.Password+"'"
                        + ",'"+this.FlagActivo+"'"
                        + ")");
//                for (int i=50;i<500;i++){
////                    Random a = new Random();
//                       st.executeUpdate("INSERT INTO USUARIO (Id_Usuario ,Nombre ,Password )VALUES("+ i
//                        + ",'"+ "marandool" +"'"
//                        + ",'"+"fiojriof878" +"'"
//                        + ")");
//              
//               }
                
                st.close(); 
              this.ReturnVal=0;
            }
            if (this.Accion == 2){//CREACION DE UNA TABLA FISICA EN UNA BASE DE DATOS
              st.executeUpdate("CREATE TABLE USUARIO("
                                + "Id_Usuario INT primary Key GENERATED BY DEFAULT AS IDENTITY,"
                                + "Nombre VARCHAR(100),"
                                + "Password VARCHAR(100),"
                                + "FlagActivo Char(10))");
              st.close(); 
              this.ReturnVal=0;
            }
            if (this.Accion == 3){//ELIMINACION DE UNA TABLA FISICA EN UNA BASE DE DATOS
              st.executeUpdate("DROP TABLE USUARIO");
              st.close(); 
              this.ReturnVal=0;
            }
        } catch (Exception e) {
            System.out.println(e);
            this.ReturnVal=-1;
        }        

    }
    public p_Usuario_ins(Connection strCn,UsuarioBE objUsuarioBE) {
        this.Accion     = objUsuarioBE.getAccion();
        this.Id_Usuario = objUsuarioBE.getId_Usuario();
        this.Nombre     = objUsuarioBE.getNombre();
        this.Password   = objUsuarioBE.getPassword();
        Statement st=null;
        try {
            st = strCn.createStatement();
            //        this.ReturVal = ReturVal;
            if (this.Accion == 1){
//              st.executeUpdate("CREATE TABLE USUARIO(Id_Usuario INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,Nombre VARCHAR(100),Password VARCHAR(100))");
                st.executeUpdate("INSERT INTO USUARIO (Nombre ,Password )VALUES("
                        + "'"+ this.Nombre + "'"
                        + ",'"+this.Password+"'"
                        + ")");
//                for (int i=50;i<500;i++){
////                    Random a = new Random();
//                       st.executeUpdate("INSERT INTO USUARIO (Id_Usuario ,Nombre ,Password )VALUES("+ i
//                        + ",'"+ "marandool" +"'"
//                        + ",'"+"fiojriof878" +"'"
//                        + ")");
//              
//               }
                
//                st.close(); 
              this.ReturnVal=0;
            }
            if (this.Accion == 2){//CREACION DE UNA TABLA FISICA EN UNA BASE DE DATOS
              st.executeUpdate("CREATE TABLE USUARIO(Id_Usuario INT primary Key GENERATED BY DEFAULT AS IDENTITY,Nombre VARCHAR(100),Password VARCHAR(100))");
//              st.close(); 
              this.ReturnVal=0;
            }
            if (this.Accion == 3){//ELIMINACION DE UNA TABLA FISICA EN UNA BASE DE DATOS
              st.executeUpdate("DROP TABLE USUARIO");
//              st.close(); 
              this.ReturnVal=0;
            }
        } catch (Exception e) {
            System.out.println(e);
            this.ReturnVal=-1;
        }        

    }
    public int getReturVal() {
        return ReturnVal;
    }

    public void setReturVal(int ReturVal) {
        this.ReturnVal = ReturVal;
    }
    
}
